"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ResourceState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ResourceStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESOURCE_STATE_UNSPECIFIED: _ResourceState.ValueType  # 0
    NORMAL: _ResourceState.ValueType  # 1
    """publish accessable"""

    UNDER_REVIEW: _ResourceState.ValueType  # 2
    """Only visiable to admin and author"""

    HIDDEN: _ResourceState.ValueType  # 3
    """Only visiable to admin and author"""

    SCHEDULED_DELETE: _ResourceState.ValueType  # 4
    """Only visiable to admin"""

    DELETED: _ResourceState.ValueType  # 5
    """Only visiable to admin"""

class ResourceState(_ResourceState, metaclass=_ResourceStateEnumTypeWrapper):
    pass

RESOURCE_STATE_UNSPECIFIED: ResourceState.ValueType  # 0
NORMAL: ResourceState.ValueType  # 1
"""publish accessable"""

UNDER_REVIEW: ResourceState.ValueType  # 2
"""Only visiable to admin and author"""

HIDDEN: ResourceState.ValueType  # 3
"""Only visiable to admin and author"""

SCHEDULED_DELETE: ResourceState.ValueType  # 4
"""Only visiable to admin"""

DELETED: ResourceState.ValueType  # 5
"""Only visiable to admin"""

global___ResourceState = ResourceState


class _Action:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Action.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACTION_UNSPECIFIED: _Action.ValueType  # 0
    CREATE: _Action.ValueType  # 1
    DELETE: _Action.ValueType  # 2
    UPDATE: _Action.ValueType  # 3
    SELECT: _Action.ValueType  # 4
    LIKE: _Action.ValueType  # 11
    """social"""

    UPVOTE: _Action.ValueType  # 12
    SUBSCRIBE: _Action.ValueType  # 13
    DISLIKE: _Action.ValueType  # 14
    DOWNLOAD: _Action.ValueType  # 21
    """misc"""

class Action(_Action, metaclass=_ActionEnumTypeWrapper):
    pass

ACTION_UNSPECIFIED: Action.ValueType  # 0
CREATE: Action.ValueType  # 1
DELETE: Action.ValueType  # 2
UPDATE: Action.ValueType  # 3
SELECT: Action.ValueType  # 4
LIKE: Action.ValueType  # 11
"""social"""

UPVOTE: Action.ValueType  # 12
SUBSCRIBE: Action.ValueType  # 13
DISLIKE: Action.ValueType  # 14
DOWNLOAD: Action.ValueType  # 21
"""misc"""

global___Action = Action


class CreatePackageRequest(google.protobuf.message.Message):
    """package related

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PACKAGE_FIELD_NUMBER: builtins.int
    parent: typing.Text
    @property
    def package(self) -> global___Package: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        package: typing.Optional[global___Package] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["package",b"package"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["package",b"package","parent",b"parent"]) -> None: ...
global___CreatePackageRequest = CreatePackageRequest

class GetPackageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `categories/123/packages/456`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___GetPackageRequest = GetPackageRequest

class UpdatePackageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PACKAGE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def package(self) -> global___Package: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        package: typing.Optional[global___Package] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["package",b"package","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["package",b"package","update_mask",b"update_mask"]) -> None: ...
global___UpdatePackageRequest = UpdatePackageRequest

class DeletePackageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeletePackageRequest = DeletePackageRequest

class ListPackagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx/packages/xxx`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListPackagesRequest = ListPackagesRequest

class ListPackagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PACKAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Package]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        packages: typing.Optional[typing.Iterable[global___Package]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","packages",b"packages"]) -> None: ...
global___ListPackagesResponse = ListPackagesResponse

class SearchPackagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    QUERY_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    query: typing.Text
    """Plain text will result as partial match on PackageName"""

    page_size: builtins.int
    page_token: typing.Text
    def __init__(self,
        *,
        query: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["page_size",b"page_size","page_token",b"page_token","query",b"query"]) -> None: ...
global___SearchPackagesRequest = SearchPackagesRequest

class SearchPackagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PACKAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Package]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        packages: typing.Optional[typing.Iterable[global___Package]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","packages",b"packages"]) -> None: ...
global___SearchPackagesResponse = SearchPackagesResponse

class GetBinaryRequest(google.protobuf.message.Message):
    """binary

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___GetBinaryRequest = GetBinaryRequest

class UploadBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    BINARY_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    DOWNLOAD_METHOD_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    SIRE_VERSION_FIELD_NUMBER: builtins.int
    SIRE_AUTO_CONVERT_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """categories/xxx/packages/xxxx"""

    @property
    def binary(self) -> global___Binary: ...
    data: builtins.bytes
    download_method: typing.Text
    url: typing.Text
    sire_version: builtins.int
    sire_auto_convert: builtins.bool
    def __init__(self,
        *,
        parent: typing.Text = ...,
        binary: typing.Optional[global___Binary] = ...,
        data: builtins.bytes = ...,
        download_method: typing.Text = ...,
        url: typing.Text = ...,
        sire_version: builtins.int = ...,
        sire_auto_convert: builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["binary",b"binary","data",b"data","download_method",b"download_method","resource",b"resource","url",b"url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary",b"binary","data",b"data","download_method",b"download_method","parent",b"parent","resource",b"resource","sire_auto_convert",b"sire_auto_convert","sire_version",b"sire_version","url",b"url"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["resource",b"resource"]) -> typing.Optional[typing_extensions.Literal["data","download_method","url"]]: ...
global___UploadBinaryRequest = UploadBinaryRequest

class CreateBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    BINARY_FIELD_NUMBER: builtins.int
    parent: typing.Text
    @property
    def binary(self) -> global___Binary: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        binary: typing.Optional[global___Binary] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["binary",b"binary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary",b"binary","parent",b"parent"]) -> None: ...
global___CreateBinaryRequest = CreateBinaryRequest

class BatchGetBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_ID_FIELD_NUMBER: builtins.int
    @property
    def binary_id(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        binary_id: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary_id",b"binary_id"]) -> None: ...
global___BatchGetBinaryRequest = BatchGetBinaryRequest

class BatchGetBinaryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARIES_FIELD_NUMBER: builtins.int
    @property
    def binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Binary]: ...
    def __init__(self,
        *,
        binaries: typing.Optional[typing.Iterable[global___Binary]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["binaries",b"binaries"]) -> None: ...
global___BatchGetBinaryResponse = BatchGetBinaryResponse

class DownloadBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DownloadBinaryRequest = DownloadBinaryRequest

class DeleteBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteBinaryRequest = DeleteBinaryRequest

class UpdateBinaryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def binary(self) -> global___Binary: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        binary: typing.Optional[global___Binary] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["binary",b"binary","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary",b"binary","update_mask",b"update_mask"]) -> None: ...
global___UpdateBinaryRequest = UpdateBinaryRequest

class ListBinariesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. `categories/123/packages/456`"""

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListBinariesRequest = ListBinariesRequest

class ListBinariesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARIES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Binary]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        binaries: typing.Optional[typing.Iterable[global___Binary]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["binaries",b"binaries","next_page_token",b"next_page_token"]) -> None: ...
global___ListBinariesResponse = ListBinariesResponse

class UploadImageRequest(google.protobuf.message.Message):
    """image

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """categories/xxx/packages/xxx or users/user_id"""

    image: builtins.bytes
    def __init__(self,
        *,
        parent: typing.Text = ...,
        image: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["image",b"image","parent",b"parent"]) -> None: ...
global___UploadImageRequest = UploadImageRequest

class CreateImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    IN_DESCRIPTION_FIELD_NUMBER: builtins.int
    parent: typing.Text
    url: typing.Text
    in_description: builtins.bool
    def __init__(self,
        *,
        parent: typing.Text = ...,
        url: typing.Text = ...,
        in_description: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_description",b"in_description","parent",b"parent","url",b"url"]) -> None: ...
global___CreateImageRequest = CreateImageRequest

class CreateThreadRequest(google.protobuf.message.Message):
    """Threads

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    THREAD_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. ``, `categories/123/packages/456`"""

    @property
    def thread(self) -> global___Thread: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        thread: typing.Optional[global___Thread] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["thread",b"thread"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent",b"parent","thread",b"thread"]) -> None: ...
global___CreateThreadRequest = CreateThreadRequest

class GetThreadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. ``, `categories/123/packages/456/threads/123`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___GetThreadRequest = GetThreadRequest

class ListThreadsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx/packages/xxx`
    `website`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListThreadsRequest = ListThreadsRequest

class ListThreadsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    THREADS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def threads(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Thread]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        threads: typing.Optional[typing.Iterable[global___Thread]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","threads",b"threads"]) -> None: ...
global___ListThreadsResponse = ListThreadsResponse

class UpdateThreadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    THREAD_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def thread(self) -> global___Thread: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        thread: typing.Optional[global___Thread] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["thread",b"thread","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["thread",b"thread","update_mask",b"update_mask"]) -> None: ...
global___UpdateThreadRequest = UpdateThreadRequest

class DeleteThreadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. ``, `categories/123/packages/456/threads/123`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteThreadRequest = DeleteThreadRequest

class CreateCommentRequest(google.protobuf.message.Message):
    """Comments"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. ``, `categories/123/packages/456`"""

    @property
    def comment(self) -> global___Comment: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        comment: typing.Optional[global___Comment] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["comment",b"comment"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["comment",b"comment","parent",b"parent"]) -> None: ...
global___CreateCommentRequest = CreateCommentRequest

class DeleteCommentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `comments/123`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteCommentRequest = DeleteCommentRequest

class UpdateCommentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMENT_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def comment(self) -> global___Comment: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        comment: typing.Optional[global___Comment] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["comment",b"comment","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["comment",b"comment","update_mask",b"update_mask"]) -> None: ...
global___UpdateCommentRequest = UpdateCommentRequest

class ListCommentsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx/packages/xxx`
    `website`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListCommentsRequest = ListCommentsRequest

class ListCommentsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    COMMENTS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def comments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Comment]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        comments: typing.Optional[typing.Iterable[global___Comment]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["comments",b"comments","next_page_token",b"next_page_token"]) -> None: ...
global___ListCommentsResponse = ListCommentsResponse

class CreateReplyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    REPLY_FIELD_NUMBER: builtins.int
    parent: typing.Text
    @property
    def reply(self) -> global___Reply: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        reply: typing.Optional[global___Reply] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reply",b"reply"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent",b"parent","reply",b"reply"]) -> None: ...
global___CreateReplyRequest = CreateReplyRequest

class DeleteReplyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteReplyRequest = DeleteReplyRequest

class UpdateReplyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REPLY_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def reply(self) -> global___Reply: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        reply: typing.Optional[global___Reply] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reply",b"reply","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reply",b"reply","update_mask",b"update_mask"]) -> None: ...
global___UpdateReplyRequest = UpdateReplyRequest

class CreateArticleRequest(google.protobuf.message.Message):
    """Article"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    ARTICLE_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Only support article at website level.
    Expected value is ``.
    """

    @property
    def article(self) -> global___Article: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        article: typing.Optional[global___Article] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["article",b"article"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["article",b"article","parent",b"parent"]) -> None: ...
global___CreateArticleRequest = CreateArticleRequest

class GetArticleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """The name of Articile. E.g. `articles/12345`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___GetArticleRequest = GetArticleRequest

class ListArticlesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. `` which is for website wide articles."""

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListArticlesRequest = ListArticlesRequest

class ListArticlesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARTICLES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def articles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Article]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        articles: typing.Optional[typing.Iterable[global___Article]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["articles",b"articles","next_page_token",b"next_page_token"]) -> None: ...
global___ListArticlesResponse = ListArticlesResponse

class UpdateArticleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ARTICLE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def article(self) -> global___Article: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        article: typing.Optional[global___Article] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["article",b"article","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["article",b"article","update_mask",b"update_mask"]) -> None: ...
global___UpdateArticleRequest = UpdateArticleRequest

class DeleteArticleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Article name. E.g. `articles/12345`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteArticleRequest = DeleteArticleRequest

class GetUserRequest(google.protobuf.message.Message):
    """user

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `users/123`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___GetUserRequest = GetUserRequest

class GetUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["user",b"user"]) -> None: ...
global___GetUserResponse = GetUserResponse

class SignInRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTITY_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    identity: typing.Text
    """Username or email"""

    password: typing.Text
    def __init__(self,
        *,
        identity: typing.Text = ...,
        password: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["identity",b"identity","password",b"password"]) -> None: ...
global___SignInRequest = SignInRequest

class SignInResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    SID_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    sid: typing.Text
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        sid: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["sid",b"sid","user",b"user"]) -> None: ...
global___SignInResponse = SignInResponse

class SignOutRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___SignOutRequest = SignOutRequest

class CreateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    VERIFICATION_CODE_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. ``"""

    @property
    def user(self) -> global___User: ...
    password: typing.Text
    verification_code: typing.Text
    def __init__(self,
        *,
        parent: typing.Text = ...,
        user: typing.Optional[global___User] = ...,
        password: typing.Text = ...,
        verification_code: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent",b"parent","password",b"password","user",b"user","verification_code",b"verification_code"]) -> None: ...
global___CreateUserRequest = CreateUserRequest

class CreateUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    SID_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    sid: typing.Text
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        sid: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["sid",b"sid","user",b"user"]) -> None: ...
global___CreateUserResponse = CreateUserResponse

class UpdateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update_mask",b"update_mask","user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["update_mask",b"update_mask","user",b"user"]) -> None: ...
global___UpdateUserRequest = UpdateUserRequest

class UpdatePasswordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    VERIFICATION_CODE_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Field `name` in User. E.g. `users/123`."""

    password: typing.Text
    verification_code: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        password: typing.Text = ...,
        verification_code: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","password",b"password","verification_code",b"verification_code"]) -> None: ...
global___UpdatePasswordRequest = UpdatePasswordRequest

class ListUsersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx/packages/xxx`
    `website`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListUsersRequest = ListUsersRequest

class ListUsersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___User]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        users: typing.Optional[typing.Iterable[global___User]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","users",b"users"]) -> None: ...
global___ListUsersResponse = ListUsersResponse

class SendVerificationCodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EMAIL_FIELD_NUMBER: builtins.int
    email: typing.Text
    def __init__(self,
        *,
        email: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email",b"email"]) -> None: ...
global___SendVerificationCodeRequest = SendVerificationCodeRequest

class VerifyEmailRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EMAIL_FIELD_NUMBER: builtins.int
    VERIFICATION_CODE_FIELD_NUMBER: builtins.int
    email: typing.Text
    verification_code: typing.Text
    def __init__(self,
        *,
        email: typing.Text = ...,
        verification_code: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["email",b"email","verification_code",b"verification_code"]) -> None: ...
global___VerifyEmailRequest = VerifyEmailRequest

class VerifyEmailResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OK_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    @property
    def user(self) -> global___User: ...
    def __init__(self,
        *,
        ok: builtins.bool = ...,
        user: typing.Optional[global___User] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ok",b"ok","user",b"user"]) -> None: ...
global___VerifyEmailResponse = VerifyEmailResponse

class ValidateNewUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    def __init__(self,
        *,
        user: typing.Optional[global___User] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["user",b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["user",b"user"]) -> None: ...
global___ValidateNewUserRequest = ValidateNewUserRequest

class ListActivitiesRequest(google.protobuf.message.Message):
    """activities related"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx/packages/xxx`
    `website`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListActivitiesRequest = ListActivitiesRequest

class ListActivitiesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ACTIVITIES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def activities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Activity]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        activities: typing.Optional[typing.Iterable[global___Activity]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["activities",b"activities","next_page_token",b"next_page_token"]) -> None: ...
global___ListActivitiesResponse = ListActivitiesResponse

class ListNotificationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    Currently, the value will always be overrided to `create_time desc`.
    """

    filter: typing.Text
    """Support syntax like `field_name = value`
    E.g. `receiver = 12345`
    """

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListNotificationsRequest = ListNotificationsRequest

class ListNotificationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    next_page_token: typing.Text
    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Notification]: ...
    def __init__(self,
        *,
        next_page_token: typing.Text = ...,
        notifications: typing.Optional[typing.Iterable[global___Notification]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","notifications",b"notifications"]) -> None: ...
global___ListNotificationsResponse = ListNotificationsResponse

class UpdateNotificationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NOTIFICATION_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def notification(self) -> global___Notification: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        notification: typing.Optional[global___Notification] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["notification",b"notification","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["notification",b"notification","update_mask",b"update_mask"]) -> None: ...
global___UpdateNotificationRequest = UpdateNotificationRequest

class CreateTagRequest(google.protobuf.message.Message):
    """tag related"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. `categories/123`"""

    @property
    def tag(self) -> global___Tag: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        tag: typing.Optional[global___Tag] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["tag",b"tag"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent",b"parent","tag",b"tag"]) -> None: ...
global___CreateTagRequest = CreateTagRequest

class ListTagsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `categories/xxx`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListTagsRequest = ListTagsRequest

class ListTagsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TAGS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tag]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        tags: typing.Optional[typing.Iterable[global___Tag]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","tags",b"tags"]) -> None: ...
global___ListTagsResponse = ListTagsResponse

class DeleteTagRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `{parent}/tags/{tag_id}`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteTagRequest = DeleteTagRequest

class GetStatisticRequest(google.protobuf.message.Message):
    """"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATE_FIELD_NUMBER: builtins.int
    date: typing.Text
    def __init__(self,
        *,
        date: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["date",b"date"]) -> None: ...
global___GetStatisticRequest = GetStatisticRequest

class GetAdminMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___GetAdminMessageRequest = GetAdminMessageRequest

class CreateSubscriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """E.g. ``, `users/123`"""

    @property
    def subscription(self) -> global___Subscription: ...
    def __init__(self,
        *,
        parent: typing.Text = ...,
        subscription: typing.Optional[global___Subscription] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["subscription",b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["parent",b"parent","subscription",b"subscription"]) -> None: ...
global___CreateSubscriptionRequest = CreateSubscriptionRequest

class ListSubscriptionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: typing.Text
    """Supported values:
    `users/123`
    """

    page_size: builtins.int
    page_token: typing.Text
    order_by: typing.Text
    """Values should be a comma separated list of fields. For example: "foo,bar".
    The default sorting order is ascending. To specify descending order for a
    field, users append a " desc" suffix;
      for example: "foo desc, bar".
    """

    filter: typing.Text
    """Support syntax like `field_name = value`"""

    def __init__(self,
        *,
        parent: typing.Text = ...,
        page_size: builtins.int = ...,
        page_token: typing.Text = ...,
        order_by: typing.Text = ...,
        filter: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter",b"filter","order_by",b"order_by","page_size",b"page_size","page_token",b"page_token","parent",b"parent"]) -> None: ...
global___ListSubscriptionsRequest = ListSubscriptionsRequest

class ListSubscriptionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def subscriptions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Subscription]: ...
    next_page_token: typing.Text
    def __init__(self,
        *,
        subscriptions: typing.Optional[typing.Iterable[global___Subscription]] = ...,
        next_page_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token",b"next_page_token","subscriptions",b"subscriptions"]) -> None: ...
global___ListSubscriptionsResponse = ListSubscriptionsResponse

class UpdateSubscriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def subscription(self) -> global___Subscription: ...
    @property
    def update_mask(self) -> global___FieldMask: ...
    def __init__(self,
        *,
        subscription: typing.Optional[global___Subscription] = ...,
        update_mask: typing.Optional[global___FieldMask] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["subscription",b"subscription","update_mask",b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["subscription",b"subscription","update_mask",b"update_mask"]) -> None: ...
global___UpdateSubscriptionRequest = UpdateSubscriptionRequest

class DeleteSubscriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `user/123/subscriptions/567`"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___DeleteSubscriptionRequest = DeleteSubscriptionRequest

class UnSubscribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUBSCRIBED_RESOURCE_FIELD_NUMBER: builtins.int
    SUBSCRIBER_ID_FIELD_NUMBER: builtins.int
    subscribed_resource: typing.Text
    """The name of the resource being subscribed. E.g. `users/123`."""

    subscriber_id: builtins.int
    def __init__(self,
        *,
        subscribed_resource: typing.Text = ...,
        subscriber_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["subscribed_resource",b"subscribed_resource","subscriber_id",b"subscriber_id"]) -> None: ...
global___UnSubscribeRequest = UnSubscribeRequest

class Empty(google.protobuf.message.Message):
    """Types

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___Empty = Empty

class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: builtins.int
    message: typing.Text
    def __init__(self,
        *,
        code: builtins.int = ...,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code",b"code","message",b"message"]) -> None: ...
global___Status = Status

class Package(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    IMAGE_URLS_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    DOWNLOAD_COUNT_FIELD_NUMBER: builtins.int
    LIKE_COUNT_FIELD_NUMBER: builtins.int
    DISLIKE_COUNT_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `categories/123/package/456`"""

    package_name: typing.Text
    description: typing.Text
    create_time: typing.Text
    update_time: typing.Text
    state: global___ResourceState.ValueType
    author_id: builtins.int
    @property
    def image_urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tag]: ...
    download_count: builtins.int
    """"""

    like_count: builtins.int
    dislike_count: builtins.int
    def __init__(self,
        *,
        name: typing.Text = ...,
        package_name: typing.Text = ...,
        description: typing.Text = ...,
        create_time: typing.Text = ...,
        update_time: typing.Text = ...,
        state: global___ResourceState.ValueType = ...,
        author_id: builtins.int = ...,
        image_urls: typing.Optional[typing.Iterable[typing.Text]] = ...,
        tags: typing.Optional[typing.Iterable[global___Tag]] = ...,
        download_count: builtins.int = ...,
        like_count: builtins.int = ...,
        dislike_count: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["author_id",b"author_id","create_time",b"create_time","description",b"description","dislike_count",b"dislike_count","download_count",b"download_count","image_urls",b"image_urls","like_count",b"like_count","name",b"name","package_name",b"package_name","state",b"state","tags",b"tags","update_time",b"update_time"]) -> None: ...
global___Package = Package

class Binary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_ID_FIELD_NUMBER: builtins.int
    PACKAGE_ID_FIELD_NUMBER: builtins.int
    DOWNLOAD_COUNT_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    FILE_FIELD_NUMBER: builtins.int
    DOWNLOAD_METHOD_FIELD_NUMBER: builtins.int
    binary_id: builtins.int
    package_id: builtins.int
    download_count: builtins.int
    @property
    def version(self) -> global___Version: ...
    description: typing.Text
    create_time: typing.Text
    tag: typing.Text
    size: typing.Text
    """human readable size. E.g. 20M, 1.2G"""

    name: typing.Text
    """resource name like `categories/123/packages/456/binaries/789`"""

    update_time: typing.Text
    @property
    def file(self) -> global___File: ...
    download_method: typing.Text
    def __init__(self,
        *,
        binary_id: builtins.int = ...,
        package_id: builtins.int = ...,
        download_count: builtins.int = ...,
        version: typing.Optional[global___Version] = ...,
        description: typing.Text = ...,
        create_time: typing.Text = ...,
        tag: typing.Text = ...,
        size: typing.Text = ...,
        name: typing.Text = ...,
        update_time: typing.Text = ...,
        file: typing.Optional[global___File] = ...,
        download_method: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["download_method",b"download_method","file",b"file","resource",b"resource","version",b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["binary_id",b"binary_id","create_time",b"create_time","description",b"description","download_count",b"download_count","download_method",b"download_method","file",b"file","name",b"name","package_id",b"package_id","resource",b"resource","size",b"size","tag",b"tag","update_time",b"update_time","version",b"version"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["resource",b"resource"]) -> typing.Optional[typing_extensions.Literal["file","download_method"]]: ...
global___Binary = Binary

class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _UserType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _UserTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[User._UserType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_TYPE_UNSPECIFIED: User._UserType.ValueType  # 0
        ADMIN: User._UserType.ValueType  # 1
        """System maintainer"""

        TESTER: User._UserType.ValueType  # 2
        REGULAR: User._UserType.ValueType  # 11
        """Customers"""

    class UserType(_UserType, metaclass=_UserTypeEnumTypeWrapper):
        pass

    USER_TYPE_UNSPECIFIED: User.UserType.ValueType  # 0
    ADMIN: User.UserType.ValueType  # 1
    """System maintainer"""

    TESTER: User.UserType.ValueType  # 2
    REGULAR: User.UserType.ValueType  # 11
    """Customers"""


    NAME_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    IMAGE_URL_FIELD_NUMBER: builtins.int
    WEBSITE_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    SUBSCRIBER_COUNT_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: typing.Text
    username: typing.Text
    email: typing.Text
    type: global___User.UserType.ValueType
    image_url: typing.Text
    website: typing.Text
    user_id: builtins.int
    """This field is parsed from `name`.
    Field `name` should be preferred when possible. Should be used for legacy
    use cases.
    [ OUTPUT_ONLY ]
    """

    subscriber_count: builtins.int
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    def __init__(self,
        *,
        name: typing.Text = ...,
        username: typing.Text = ...,
        email: typing.Text = ...,
        type: global___User.UserType.ValueType = ...,
        image_url: typing.Text = ...,
        website: typing.Text = ...,
        user_id: builtins.int = ...,
        subscriber_count: builtins.int = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_time",b"create_time","email",b"email","image_url",b"image_url","name",b"name","subscriber_count",b"subscriber_count","type",b"type","update_time",b"update_time","user_id",b"user_id","username",b"username","website",b"website"]) -> None: ...
global___User = User

class Version(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAJOR_FIELD_NUMBER: builtins.int
    MINOR_FIELD_NUMBER: builtins.int
    PATCH_FIELD_NUMBER: builtins.int
    major: builtins.int
    minor: builtins.int
    patch: builtins.int
    def __init__(self,
        *,
        major: builtins.int = ...,
        minor: builtins.int = ...,
        patch: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["major",b"major","minor",b"minor","patch",b"patch"]) -> None: ...
global___Version = Version

class Statistic(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VISIT_COUNT_FIELD_NUMBER: builtins.int
    DOWNLOAD_COUNT_FIELD_NUMBER: builtins.int
    visit_count: builtins.int
    download_count: builtins.int
    def __init__(self,
        *,
        visit_count: builtins.int = ...,
        download_count: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["download_count",b"download_count","visit_count",b"visit_count"]) -> None: ...
global___Statistic = Statistic

class Url(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    URL_FIELD_NUMBER: builtins.int
    url: typing.Text
    def __init__(self,
        *,
        url: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["url",b"url"]) -> None: ...
global___Url = Url

class Thread(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    PINNED_FIELD_NUMBER: builtins.int
    LATEST_COMMENTED_TIME_FIELD_NUMBER: builtins.int
    LATEST_COMMENTER_ID_FIELD_NUMBER: builtins.int
    VIEW_COUNT_FIELD_NUMBER: builtins.int
    LIKE_COUNT_FIELD_NUMBER: builtins.int
    COMMENT_COUNT_FIELD_NUMBER: builtins.int
    REPLY_COUNT_FIELD_NUMBER: builtins.int
    name: typing.Text
    """E.g. `categories/123/packages/456/threads/789`"""

    subject: typing.Text
    content: typing.Text
    author_id: builtins.int
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    state: global___ResourceState.ValueType
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    pinned: builtins.bool
    @property
    def latest_commented_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    latest_commenter_id: builtins.int
    """[ OUTPUT_ONLY ]"""

    view_count: builtins.int
    like_count: builtins.int
    comment_count: builtins.int
    reply_count: builtins.int
    def __init__(self,
        *,
        name: typing.Text = ...,
        subject: typing.Text = ...,
        content: typing.Text = ...,
        author_id: builtins.int = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        state: global___ResourceState.ValueType = ...,
        tags: typing.Optional[typing.Iterable[typing.Text]] = ...,
        pinned: builtins.bool = ...,
        latest_commented_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        latest_commenter_id: builtins.int = ...,
        view_count: builtins.int = ...,
        like_count: builtins.int = ...,
        comment_count: builtins.int = ...,
        reply_count: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","latest_commented_time",b"latest_commented_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["author_id",b"author_id","comment_count",b"comment_count","content",b"content","create_time",b"create_time","latest_commented_time",b"latest_commented_time","latest_commenter_id",b"latest_commenter_id","like_count",b"like_count","name",b"name","pinned",b"pinned","reply_count",b"reply_count","state",b"state","subject",b"subject","tags",b"tags","update_time",b"update_time","view_count",b"view_count"]) -> None: ...
global___Thread = Thread

class Comment(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    UPVOTE_COUNT_FIELD_NUMBER: builtins.int
    REPLIES_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    text: typing.Text
    author_id: builtins.int
    upvote_count: builtins.int
    @property
    def replies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Reply]:
        """[ OUTPUT_ONLY ]"""
        pass
    index: builtins.int
    """The index of the comment within its parent. The first index is 1."""

    def __init__(self,
        *,
        name: typing.Text = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        text: typing.Text = ...,
        author_id: builtins.int = ...,
        upvote_count: builtins.int = ...,
        replies: typing.Optional[typing.Iterable[global___Reply]] = ...,
        index: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["author_id",b"author_id","create_time",b"create_time","index",b"index","name",b"name","replies",b"replies","text",b"text","update_time",b"update_time","upvote_count",b"upvote_count"]) -> None: ...
global___Comment = Comment

class Reply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    UPVOTE_COUNT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    text: typing.Text
    author_id: builtins.int
    upvote_count: builtins.int
    def __init__(self,
        *,
        name: typing.Text = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        text: typing.Text = ...,
        author_id: builtins.int = ...,
        upvote_count: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["author_id",b"author_id","create_time",b"create_time","name",b"name","text",b"text","update_time",b"update_time","upvote_count",b"upvote_count"]) -> None: ...
global___Reply = Reply

class Tag(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    TAG_NAME_FIELD_NUMBER: builtins.int
    MUTABLE_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Resource name. E.g. 'categories/123/tags/456'"""

    tag_name: typing.Text
    """A string not longer than 8."""

    mutable: builtins.bool
    """Whether a user can update (assign or remove) this tag.
    A immutable tag can only be updated by backend. E.g. `SIRE 1`, `SIRE 2`
    """

    def __init__(self,
        *,
        name: typing.Text = ...,
        tag_name: typing.Text = ...,
        mutable: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mutable",b"mutable","name",b"name","tag_name",b"tag_name"]) -> None: ...
global___Tag = Tag

class AdminMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text
    def __init__(self,
        *,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message"]) -> None: ...
global___AdminMessage = AdminMessage

class Auth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OAUTH2_TOKEN_FIELD_NUMBER: builtins.int
    oauth2_token: typing.Text
    def __init__(self,
        *,
        oauth2_token: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["oauth2_token",b"oauth2_token"]) -> None: ...
global___Auth = Auth

class Activity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    RESOURCE_VIEW_FIELD_NUMBER: builtins.int
    name: typing.Text
    create_time: typing.Text
    action: global___Action.ValueType
    @property
    def resource_view(self) -> global___ResourceView: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        create_time: typing.Text = ...,
        action: global___Action.ValueType = ...,
        resource_view: typing.Optional[global___ResourceView] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resource_view",b"resource_view"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["action",b"action","create_time",b"create_time","name",b"name","resource_view",b"resource_view"]) -> None: ...
global___Activity = Activity

class Notification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SENDER_ID_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    UNREAD_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    IMAGE_PREVIEW_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Resource name. E.g. 'users/123/notifications/12345'"""

    sender_id: builtins.int
    """[ OUTPUT_ONLY ]"""

    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    unread: builtins.bool
    content: typing.Text
    """[ OUTPUT_ONLY ]"""

    image_preview: typing.Text
    """[ OUTPUT_ONLY ]"""

    link: typing.Text
    """[ OUTPUT_ONLY ]"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        sender_id: builtins.int = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        unread: builtins.bool = ...,
        content: typing.Text = ...,
        image_preview: typing.Text = ...,
        link: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["content",b"content","create_time",b"create_time","image_preview",b"image_preview","link",b"link","name",b"name","sender_id",b"sender_id","unread",b"unread","update_time",b"update_time"]) -> None: ...
global___Notification = Notification

class ResourceView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    IMAGE_URL_FIELD_NUMBER: builtins.int
    name: typing.Text
    display_name: typing.Text
    description: typing.Text
    image_url: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        display_name: typing.Text = ...,
        description: typing.Text = ...,
        image_url: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description",b"description","display_name",b"display_name","image_url",b"image_url","name",b"name"]) -> None: ...
global___ResourceView = ResourceView

class Article(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    VIEW_COUNT_FIELD_NUMBER: builtins.int
    LIKE_COUNT_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Resource name. E.g. 'articles/12345'"""

    subject: typing.Text
    content: typing.Text
    author_id: builtins.int
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """[ OUTPUT_ONLY ]"""
        pass
    state: global___ResourceState.ValueType
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    view_count: builtins.int
    like_count: builtins.int
    def __init__(self,
        *,
        name: typing.Text = ...,
        subject: typing.Text = ...,
        content: typing.Text = ...,
        author_id: builtins.int = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        state: global___ResourceState.ValueType = ...,
        tags: typing.Optional[typing.Iterable[typing.Text]] = ...,
        view_count: builtins.int = ...,
        like_count: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["author_id",b"author_id","content",b"content","create_time",b"create_time","like_count",b"like_count","name",b"name","state",b"state","subject",b"subject","tags",b"tags","update_time",b"update_time","view_count",b"view_count"]) -> None: ...
global___Article = Article

class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Server:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ServerEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[File._Server.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SERVER_UNSPECIFIED: File._Server.ValueType  # 0
        GCS: File._Server.ValueType  # 1
        """Google Cloud Storage"""

        AWS_S3: File._Server.ValueType  # 2
        """AWS S3"""

    class Server(_Server, metaclass=_ServerEnumTypeWrapper):
        pass

    SERVER_UNSPECIFIED: File.Server.ValueType  # 0
    GCS: File.Server.ValueType  # 1
    """Google Cloud Storage"""

    AWS_S3: File.Server.ValueType  # 2
    """AWS S3"""


    FILENAME_FIELD_NUMBER: builtins.int
    EXT_FIELD_NUMBER: builtins.int
    SERVER_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    filename: typing.Text
    """E.g. `血色衣冠-安装包`"""

    ext: typing.Text
    """Please note `.` is considered part of the extension.
    E.g. `.txt`, `.png`, `.rar`, `.zip`
    """

    server: global___File.Server.ValueType
    """The file server hosting the file."""

    uri: typing.Text
    """Unique resource identifier
    E.g. categories/123/packags/456/binaries/eafsdfewasdfdfsaasdffda
    """

    def __init__(self,
        *,
        filename: typing.Text = ...,
        ext: typing.Text = ...,
        server: global___File.Server.ValueType = ...,
        uri: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ext",b"ext","filename",b"filename","server",b"server","uri",b"uri"]) -> None: ...
global___File = File

class Subscription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _SubscribeType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _SubscribeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Subscription._SubscribeType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUBSCRIBE_TYPE_UNSPECIFIED: Subscription._SubscribeType.ValueType  # 0
        ALL: Subscription._SubscribeType.ValueType  # 1
        """Receive notification on all events."""

    class SubscribeType(_SubscribeType, metaclass=_SubscribeTypeEnumTypeWrapper):
        pass

    SUBSCRIBE_TYPE_UNSPECIFIED: Subscription.SubscribeType.ValueType  # 0
    ALL: Subscription.SubscribeType.ValueType  # 1
    """Receive notification on all events."""


    NAME_FIELD_NUMBER: builtins.int
    SUBSCRIBER_ID_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: typing.Text
    """The `parent` is the resource being subscribed.
    For name `users/123/subscriptions/1`, `users/123` is the resource being
    subscribed.
    """

    subscriber_id: builtins.int
    """`user_id` of the user who should receive notifications."""

    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        [ OUTPUT_ONLY ]
        """
        pass
    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """
        [ OUTPUT_ONLY ]
        """
        pass
    type: global___Subscription.SubscribeType.ValueType
    """"""

    def __init__(self,
        *,
        name: typing.Text = ...,
        subscriber_id: builtins.int = ...,
        create_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        update_time: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        type: global___Subscription.SubscribeType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time",b"create_time","update_time",b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["create_time",b"create_time","name",b"name","subscriber_id",b"subscriber_id","type",b"type","update_time",b"update_time"]) -> None: ...
global___Subscription = Subscription

class FieldMask(google.protobuf.message.Message):
    """
    Utilities

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATHS_FIELD_NUMBER: builtins.int
    @property
    def paths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        paths: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paths",b"paths"]) -> None: ...
global___FieldMask = FieldMask
