"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PaginationOption(google.protobuf.message.Message):
    """This is an internal utility message being used to generate page_token."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    WATERMARK_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    parent: builtins.str
    page_size: builtins.int
    watermark: builtins.int
    """To indicate where were left from previous list. Could be offset other more
    sophisticated info.
    """
    order_by: builtins.str
    filter: builtins.str
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        watermark: builtins.int = ...,
        order_by: builtins.str = ...,
        filter: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter", b"filter", "order_by", b"order_by", "page_size", b"page_size", "parent", b"parent", "watermark", b"watermark"]) -> None: ...

global___PaginationOption = PaginationOption
