version: "3"

services:
  front-end:
    build:
      context: ./front-end
      args:
        CADDYFILE: Caddyfile
    environment:
      - DOMAIN=san11pk.org
    restart: always
    ports:
      - "443:443"
      - "80:80"
      # For GRPC traffic to api.${DOMAIN}
      - "8090:8090"
      # For gateway legacy traffic
      - "8081:8081"
    depends_on:
      - envoy
      - gateway

  back-end:
    build: ./back-end
    restart: always
    working_dir: /app
    volumes:
      - ./back-end/src:/app
      - ./back-end/utils:/utils
    environment:
      DB_HOST: db
    command:
      [
        "/utils/wait-for-postgres.sh",
        "db",
        "python3.8",
        "san11_platform_server.py",
      ]
    depends_on:
      - db
      - envoy

  gateway:
    build: ./back-end/gateway
    restart: always
    working_dir: /app
    command: go run main.go
    depends_on:
      - back-end

  envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    restart: always
    volumes:
      - ./back-end/envoy:/etc/envoy
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8091:8091"

  db:
    build: ./database
    restart: always
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/backup:/backup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
