version: "3"

services:
  back-end:
    build: ./back-end
    restart: always
    working_dir: /app
    volumes:
      - ./back-end/src:/app
      - ./back-end/utils:/utils
      - ../credentials:/credentials
    environment:
      STAGE: PROD
      NOTIFIER_SERVICE_ACCOUNT_FILE: '/credentials/san11-platform-notifier.json'
      AWS_CREDENTIALS_FILE: '/credentials/aws-backend.json'
      GCLOUD_CREDENTIALS_FILE: '/credentials/san11-grpc-backend.json'
      DB_HOST: db
    command: ["/utils/wait-for-postgres.sh", "db", "python3.8", "san11_platform_server.py"]
    depends_on:
      - db
      - envoy
  
  gateway:
    build: ./back-end/gateway
    restart: always
    working_dir: /app
    command: go run main.go
    depends_on:
      - back-end
    ports:
      - "8081:8081"

  envoy:
    image: envoyproxy/envoy-alpine:v1.21.6
    restart: always
    volumes:
      - ./back-end/envoy:/etc/envoy
      - ../credentials:/credentials
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8090:8090"

  db:
    build: ./database
    restart: always
    volumes: 
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/backup:/backup
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  front-end:
    build: ./front-end
    restart: always
    ports:
      - "443:443" # If using SSL with Nginx
      - "80:80"   # For standard HTTP
    depends_on:
      - back-end
