version: "3"

services:
  sut:
    build:
      context: ./back-end
      dockerfile: Dockerfile.test
    working_dir: /workspace
    volumes:
      - ./back-end:/workspace
      - ./back-end/utils:/utils
      - ./database:/database:ro
    command: ["/utils/wait-for-postgres.sh", "test_db", "make", "test"]
    environment:
      DB_HOST: test_db
      PY: python3.8
    depends_on:
      - test_db
  
  test_db:
    build: ./database
    volumes: 
      - ${TMP_DB_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
