version: "3"

services:
  back-end:
    build: ./back-end
    restart: always
    working_dir: /app
    volumes:
      - ./back-end/src:/app
      - ./back-end/utils:/utils
      - ./resources:/data
    command: ["/utils/wait-for-postgres.sh", "db", "python3.8", "san11_platform_server.py"]
    depends_on:
      - db
      - envoy

  nginx:
    image: nginx:latest
    restart: always
    volumes: 
      - ./resources:/data
      - ./back-end/nginx/conf:/etc/nginx/conf.d
    command: []
    ports:
      - "8080:8080"

  envoy:
    image: envoyproxy/envoy-alpine:v1.13.0
    restart: always
    volumes:
      - ./back-end/envoy:/etc/envoy
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
    ports:
      - "8090:8090"

  db:
    build: ./database
    restart: always
    volumes: 
      - ./database/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  front-end:
    build: ./front-end
    restart: always
    working_dir: /app
    volumes:
      - ./front-end:/app
    command: bash -c "npm install && ng serve --prod --host 0.0.0.0 --disable-host-check"
    depends_on: 
      - back-end
      - nginx
    ports:
      - "80:4200"
    
