# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import san11_platform_pb2 as san11__platform__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in san11_platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class San11PlatformStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePackage = channel.unary_unary(
                '/san11_platform.San11Platform/CreatePackage',
                request_serializer=san11__platform__pb2.CreatePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                _registered_method=True)
        self.GetPackage = channel.unary_unary(
                '/san11_platform.San11Platform/GetPackage',
                request_serializer=san11__platform__pb2.GetPackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                _registered_method=True)
        self.ListPackages = channel.unary_unary(
                '/san11_platform.San11Platform/ListPackages',
                request_serializer=san11__platform__pb2.ListPackagesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListPackagesResponse.FromString,
                _registered_method=True)
        self.UpdatePackage = channel.unary_unary(
                '/san11_platform.San11Platform/UpdatePackage',
                request_serializer=san11__platform__pb2.UpdatePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                _registered_method=True)
        self.DeletePackage = channel.unary_unary(
                '/san11_platform.San11Platform/DeletePackage',
                request_serializer=san11__platform__pb2.DeletePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                _registered_method=True)
        self.SearchPackages = channel.unary_unary(
                '/san11_platform.San11Platform/SearchPackages',
                request_serializer=san11__platform__pb2.SearchPackagesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.SearchPackagesResponse.FromString,
                _registered_method=True)
        self.CreateBinary = channel.unary_unary(
                '/san11_platform.San11Platform/CreateBinary',
                request_serializer=san11__platform__pb2.CreateBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                _registered_method=True)
        self.GetBinary = channel.unary_unary(
                '/san11_platform.San11Platform/GetBinary',
                request_serializer=san11__platform__pb2.GetBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                _registered_method=True)
        self.BatchGetBinary = channel.unary_unary(
                '/san11_platform.San11Platform/BatchGetBinary',
                request_serializer=san11__platform__pb2.BatchGetBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.BatchGetBinaryResponse.FromString,
                _registered_method=True)
        self.ListBinaries = channel.unary_unary(
                '/san11_platform.San11Platform/ListBinaries',
                request_serializer=san11__platform__pb2.ListBinariesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListBinariesResponse.FromString,
                _registered_method=True)
        self.UpdateBinary = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateBinary',
                request_serializer=san11__platform__pb2.UpdateBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                _registered_method=True)
        self.DeleteBinary = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteBinary',
                request_serializer=san11__platform__pb2.DeleteBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                _registered_method=True)
        self.DownloadBinary = channel.unary_unary(
                '/san11_platform.San11Platform/DownloadBinary',
                request_serializer=san11__platform__pb2.DownloadBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                _registered_method=True)
        self.CreateImage = channel.unary_unary(
                '/san11_platform.San11Platform/CreateImage',
                request_serializer=san11__platform__pb2.CreateImageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Url.FromString,
                _registered_method=True)
        self.CreateThread = channel.unary_unary(
                '/san11_platform.San11Platform/CreateThread',
                request_serializer=san11__platform__pb2.CreateThreadRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Thread.FromString,
                _registered_method=True)
        self.GetThread = channel.unary_unary(
                '/san11_platform.San11Platform/GetThread',
                request_serializer=san11__platform__pb2.GetThreadRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Thread.FromString,
                _registered_method=True)
        self.ListThreads = channel.unary_unary(
                '/san11_platform.San11Platform/ListThreads',
                request_serializer=san11__platform__pb2.ListThreadsRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListThreadsResponse.FromString,
                _registered_method=True)
        self.UpdateThread = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateThread',
                request_serializer=san11__platform__pb2.UpdateThreadRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Thread.FromString,
                _registered_method=True)
        self.DeleteThread = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteThread',
                request_serializer=san11__platform__pb2.DeleteThreadRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Thread.FromString,
                _registered_method=True)
        self.CreateComment = channel.unary_unary(
                '/san11_platform.San11Platform/CreateComment',
                request_serializer=san11__platform__pb2.CreateCommentRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Comment.FromString,
                _registered_method=True)
        self.ListComments = channel.unary_unary(
                '/san11_platform.San11Platform/ListComments',
                request_serializer=san11__platform__pb2.ListCommentsRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListCommentsResponse.FromString,
                _registered_method=True)
        self.UpdateComment = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateComment',
                request_serializer=san11__platform__pb2.UpdateCommentRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Comment.FromString,
                _registered_method=True)
        self.DeleteComment = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteComment',
                request_serializer=san11__platform__pb2.DeleteCommentRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Comment.FromString,
                _registered_method=True)
        self.CreateReply = channel.unary_unary(
                '/san11_platform.San11Platform/CreateReply',
                request_serializer=san11__platform__pb2.CreateReplyRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Reply.FromString,
                _registered_method=True)
        self.UpdateReply = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateReply',
                request_serializer=san11__platform__pb2.UpdateReplyRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Reply.FromString,
                _registered_method=True)
        self.DeleteReply = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteReply',
                request_serializer=san11__platform__pb2.DeleteReplyRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Reply.FromString,
                _registered_method=True)
        self.CreateArticle = channel.unary_unary(
                '/san11_platform.San11Platform/CreateArticle',
                request_serializer=san11__platform__pb2.CreateArticleRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Article.FromString,
                _registered_method=True)
        self.GetArticle = channel.unary_unary(
                '/san11_platform.San11Platform/GetArticle',
                request_serializer=san11__platform__pb2.GetArticleRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Article.FromString,
                _registered_method=True)
        self.ListArticles = channel.unary_unary(
                '/san11_platform.San11Platform/ListArticles',
                request_serializer=san11__platform__pb2.ListArticlesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListArticlesResponse.FromString,
                _registered_method=True)
        self.UpdateArticle = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateArticle',
                request_serializer=san11__platform__pb2.UpdateArticleRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Article.FromString,
                _registered_method=True)
        self.DeleteArticle = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteArticle',
                request_serializer=san11__platform__pb2.DeleteArticleRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Article.FromString,
                _registered_method=True)
        self.SignIn = channel.unary_unary(
                '/san11_platform.San11Platform/SignIn',
                request_serializer=san11__platform__pb2.SignInRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.SignInResponse.FromString,
                _registered_method=True)
        self.SignOut = channel.unary_unary(
                '/san11_platform.San11Platform/SignOut',
                request_serializer=san11__platform__pb2.SignOutRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Status.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/san11_platform.San11Platform/CreateUser',
                request_serializer=san11__platform__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/san11_platform.San11Platform/GetUser',
                request_serializer=san11__platform__pb2.GetUserRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/san11_platform.San11Platform/ListUsers',
                request_serializer=san11__platform__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateUser',
                request_serializer=san11__platform__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.User.FromString,
                _registered_method=True)
        self.SendVerificationCode = channel.unary_unary(
                '/san11_platform.San11Platform/SendVerificationCode',
                request_serializer=san11__platform__pb2.SendVerificationCodeRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Empty.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/san11_platform.San11Platform/VerifyEmail',
                request_serializer=san11__platform__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.VerifyEmailResponse.FromString,
                _registered_method=True)
        self.ValidateNewUser = channel.unary_unary(
                '/san11_platform.San11Platform/ValidateNewUser',
                request_serializer=san11__platform__pb2.ValidateNewUserRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Status.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/san11_platform.San11Platform/UpdatePassword',
                request_serializer=san11__platform__pb2.UpdatePasswordRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.User.FromString,
                _registered_method=True)
        self.ListActivities = channel.unary_unary(
                '/san11_platform.San11Platform/ListActivities',
                request_serializer=san11__platform__pb2.ListActivitiesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListActivitiesResponse.FromString,
                _registered_method=True)
        self.ToggleAction = channel.unary_unary(
                '/san11_platform.San11Platform/ToggleAction',
                request_serializer=san11__platform__pb2.ToggleActionRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ToggleActionResponse.FromString,
                _registered_method=True)
        self.ListNotifications = channel.unary_unary(
                '/san11_platform.San11Platform/ListNotifications',
                request_serializer=san11__platform__pb2.ListNotificationsRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListNotificationsResponse.FromString,
                _registered_method=True)
        self.UpdateNotification = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateNotification',
                request_serializer=san11__platform__pb2.UpdateNotificationRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Notification.FromString,
                _registered_method=True)
        self.CreateTag = channel.unary_unary(
                '/san11_platform.San11Platform/CreateTag',
                request_serializer=san11__platform__pb2.CreateTagRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Tag.FromString,
                _registered_method=True)
        self.ListTags = channel.unary_unary(
                '/san11_platform.San11Platform/ListTags',
                request_serializer=san11__platform__pb2.ListTagsRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListTagsResponse.FromString,
                _registered_method=True)
        self.DeleteTag = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteTag',
                request_serializer=san11__platform__pb2.DeleteTagRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Tag.FromString,
                _registered_method=True)
        self.GetStatistic = channel.unary_unary(
                '/san11_platform.San11Platform/GetStatistic',
                request_serializer=san11__platform__pb2.GetStatisticRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Statistic.FromString,
                _registered_method=True)
        self.GetAdminMessage = channel.unary_unary(
                '/san11_platform.San11Platform/GetAdminMessage',
                request_serializer=san11__platform__pb2.GetAdminMessageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.AdminMessage.FromString,
                _registered_method=True)
        self.CreateSubscription = channel.unary_unary(
                '/san11_platform.San11Platform/CreateSubscription',
                request_serializer=san11__platform__pb2.CreateSubscriptionRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Subscription.FromString,
                _registered_method=True)
        self.ListSubscriptioins = channel.unary_unary(
                '/san11_platform.San11Platform/ListSubscriptioins',
                request_serializer=san11__platform__pb2.ListSubscriptionsRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListSubscriptionsResponse.FromString,
                _registered_method=True)
        self.UpdateSubscription = channel.unary_unary(
                '/san11_platform.San11Platform/UpdateSubscription',
                request_serializer=san11__platform__pb2.UpdateSubscriptionRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Subscription.FromString,
                _registered_method=True)
        self.DeleteSubscription = channel.unary_unary(
                '/san11_platform.San11Platform/DeleteSubscription',
                request_serializer=san11__platform__pb2.DeleteSubscriptionRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Subscription.FromString,
                _registered_method=True)


class San11PlatformServicer(object):
    """Interface exported by the server.
    """

    def CreatePackage(self, request, context):
        """package related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBinary(self, request, context):
        """Binary related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBinaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateImage(self, request, context):
        """Image related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateThread(self, request, context):
        """Thread related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """comment related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArticle(self, request, context):
        """articles related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """User related - legacy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """User related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVerificationCode(self, request, context):
        """User related utilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateNewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActivities(self, request, context):
        """Activities reltead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTag(self, request, context):
        """Tag related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistic(self, request, context):
        """Generic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSubscription(self, request, context):
        """Subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubscriptioins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSubscription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_San11PlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePackage,
                    request_deserializer=san11__platform__pb2.CreatePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'GetPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPackage,
                    request_deserializer=san11__platform__pb2.GetPackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'ListPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackages,
                    request_deserializer=san11__platform__pb2.ListPackagesRequest.FromString,
                    response_serializer=san11__platform__pb2.ListPackagesResponse.SerializeToString,
            ),
            'UpdatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePackage,
                    request_deserializer=san11__platform__pb2.UpdatePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'DeletePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePackage,
                    request_deserializer=san11__platform__pb2.DeletePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'SearchPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPackages,
                    request_deserializer=san11__platform__pb2.SearchPackagesRequest.FromString,
                    response_serializer=san11__platform__pb2.SearchPackagesResponse.SerializeToString,
            ),
            'CreateBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBinary,
                    request_deserializer=san11__platform__pb2.CreateBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'GetBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBinary,
                    request_deserializer=san11__platform__pb2.GetBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'BatchGetBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetBinary,
                    request_deserializer=san11__platform__pb2.BatchGetBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.BatchGetBinaryResponse.SerializeToString,
            ),
            'ListBinaries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBinaries,
                    request_deserializer=san11__platform__pb2.ListBinariesRequest.FromString,
                    response_serializer=san11__platform__pb2.ListBinariesResponse.SerializeToString,
            ),
            'UpdateBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBinary,
                    request_deserializer=san11__platform__pb2.UpdateBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'DeleteBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBinary,
                    request_deserializer=san11__platform__pb2.DeleteBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'DownloadBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadBinary,
                    request_deserializer=san11__platform__pb2.DownloadBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'CreateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateImage,
                    request_deserializer=san11__platform__pb2.CreateImageRequest.FromString,
                    response_serializer=san11__platform__pb2.Url.SerializeToString,
            ),
            'CreateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThread,
                    request_deserializer=san11__platform__pb2.CreateThreadRequest.FromString,
                    response_serializer=san11__platform__pb2.Thread.SerializeToString,
            ),
            'GetThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThread,
                    request_deserializer=san11__platform__pb2.GetThreadRequest.FromString,
                    response_serializer=san11__platform__pb2.Thread.SerializeToString,
            ),
            'ListThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThreads,
                    request_deserializer=san11__platform__pb2.ListThreadsRequest.FromString,
                    response_serializer=san11__platform__pb2.ListThreadsResponse.SerializeToString,
            ),
            'UpdateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateThread,
                    request_deserializer=san11__platform__pb2.UpdateThreadRequest.FromString,
                    response_serializer=san11__platform__pb2.Thread.SerializeToString,
            ),
            'DeleteThread': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteThread,
                    request_deserializer=san11__platform__pb2.DeleteThreadRequest.FromString,
                    response_serializer=san11__platform__pb2.Thread.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=san11__platform__pb2.CreateCommentRequest.FromString,
                    response_serializer=san11__platform__pb2.Comment.SerializeToString,
            ),
            'ListComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComments,
                    request_deserializer=san11__platform__pb2.ListCommentsRequest.FromString,
                    response_serializer=san11__platform__pb2.ListCommentsResponse.SerializeToString,
            ),
            'UpdateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComment,
                    request_deserializer=san11__platform__pb2.UpdateCommentRequest.FromString,
                    response_serializer=san11__platform__pb2.Comment.SerializeToString,
            ),
            'DeleteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComment,
                    request_deserializer=san11__platform__pb2.DeleteCommentRequest.FromString,
                    response_serializer=san11__platform__pb2.Comment.SerializeToString,
            ),
            'CreateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReply,
                    request_deserializer=san11__platform__pb2.CreateReplyRequest.FromString,
                    response_serializer=san11__platform__pb2.Reply.SerializeToString,
            ),
            'UpdateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReply,
                    request_deserializer=san11__platform__pb2.UpdateReplyRequest.FromString,
                    response_serializer=san11__platform__pb2.Reply.SerializeToString,
            ),
            'DeleteReply': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReply,
                    request_deserializer=san11__platform__pb2.DeleteReplyRequest.FromString,
                    response_serializer=san11__platform__pb2.Reply.SerializeToString,
            ),
            'CreateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArticle,
                    request_deserializer=san11__platform__pb2.CreateArticleRequest.FromString,
                    response_serializer=san11__platform__pb2.Article.SerializeToString,
            ),
            'GetArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticle,
                    request_deserializer=san11__platform__pb2.GetArticleRequest.FromString,
                    response_serializer=san11__platform__pb2.Article.SerializeToString,
            ),
            'ListArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArticles,
                    request_deserializer=san11__platform__pb2.ListArticlesRequest.FromString,
                    response_serializer=san11__platform__pb2.ListArticlesResponse.SerializeToString,
            ),
            'UpdateArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateArticle,
                    request_deserializer=san11__platform__pb2.UpdateArticleRequest.FromString,
                    response_serializer=san11__platform__pb2.Article.SerializeToString,
            ),
            'DeleteArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArticle,
                    request_deserializer=san11__platform__pb2.DeleteArticleRequest.FromString,
                    response_serializer=san11__platform__pb2.Article.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=san11__platform__pb2.SignInRequest.FromString,
                    response_serializer=san11__platform__pb2.SignInResponse.SerializeToString,
            ),
            'SignOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOut,
                    request_deserializer=san11__platform__pb2.SignOutRequest.FromString,
                    response_serializer=san11__platform__pb2.Status.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=san11__platform__pb2.CreateUserRequest.FromString,
                    response_serializer=san11__platform__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=san11__platform__pb2.GetUserRequest.FromString,
                    response_serializer=san11__platform__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=san11__platform__pb2.ListUsersRequest.FromString,
                    response_serializer=san11__platform__pb2.ListUsersResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=san11__platform__pb2.UpdateUserRequest.FromString,
                    response_serializer=san11__platform__pb2.User.SerializeToString,
            ),
            'SendVerificationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVerificationCode,
                    request_deserializer=san11__platform__pb2.SendVerificationCodeRequest.FromString,
                    response_serializer=san11__platform__pb2.Empty.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=san11__platform__pb2.VerifyEmailRequest.FromString,
                    response_serializer=san11__platform__pb2.VerifyEmailResponse.SerializeToString,
            ),
            'ValidateNewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateNewUser,
                    request_deserializer=san11__platform__pb2.ValidateNewUserRequest.FromString,
                    response_serializer=san11__platform__pb2.Status.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=san11__platform__pb2.UpdatePasswordRequest.FromString,
                    response_serializer=san11__platform__pb2.User.SerializeToString,
            ),
            'ListActivities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActivities,
                    request_deserializer=san11__platform__pb2.ListActivitiesRequest.FromString,
                    response_serializer=san11__platform__pb2.ListActivitiesResponse.SerializeToString,
            ),
            'ToggleAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleAction,
                    request_deserializer=san11__platform__pb2.ToggleActionRequest.FromString,
                    response_serializer=san11__platform__pb2.ToggleActionResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=san11__platform__pb2.ListNotificationsRequest.FromString,
                    response_serializer=san11__platform__pb2.ListNotificationsResponse.SerializeToString,
            ),
            'UpdateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotification,
                    request_deserializer=san11__platform__pb2.UpdateNotificationRequest.FromString,
                    response_serializer=san11__platform__pb2.Notification.SerializeToString,
            ),
            'CreateTag': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTag,
                    request_deserializer=san11__platform__pb2.CreateTagRequest.FromString,
                    response_serializer=san11__platform__pb2.Tag.SerializeToString,
            ),
            'ListTags': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTags,
                    request_deserializer=san11__platform__pb2.ListTagsRequest.FromString,
                    response_serializer=san11__platform__pb2.ListTagsResponse.SerializeToString,
            ),
            'DeleteTag': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTag,
                    request_deserializer=san11__platform__pb2.DeleteTagRequest.FromString,
                    response_serializer=san11__platform__pb2.Tag.SerializeToString,
            ),
            'GetStatistic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistic,
                    request_deserializer=san11__platform__pb2.GetStatisticRequest.FromString,
                    response_serializer=san11__platform__pb2.Statistic.SerializeToString,
            ),
            'GetAdminMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminMessage,
                    request_deserializer=san11__platform__pb2.GetAdminMessageRequest.FromString,
                    response_serializer=san11__platform__pb2.AdminMessage.SerializeToString,
            ),
            'CreateSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSubscription,
                    request_deserializer=san11__platform__pb2.CreateSubscriptionRequest.FromString,
                    response_serializer=san11__platform__pb2.Subscription.SerializeToString,
            ),
            'ListSubscriptioins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubscriptioins,
                    request_deserializer=san11__platform__pb2.ListSubscriptionsRequest.FromString,
                    response_serializer=san11__platform__pb2.ListSubscriptionsResponse.SerializeToString,
            ),
            'UpdateSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSubscription,
                    request_deserializer=san11__platform__pb2.UpdateSubscriptionRequest.FromString,
                    response_serializer=san11__platform__pb2.Subscription.SerializeToString,
            ),
            'DeleteSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSubscription,
                    request_deserializer=san11__platform__pb2.DeleteSubscriptionRequest.FromString,
                    response_serializer=san11__platform__pb2.Subscription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'san11_platform.San11Platform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('san11_platform.San11Platform', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class San11Platform(object):
    """Interface exported by the server.
    """

    @staticmethod
    def CreatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreatePackage',
            san11__platform__pb2.CreatePackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetPackage',
            san11__platform__pb2.GetPackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListPackages',
            san11__platform__pb2.ListPackagesRequest.SerializeToString,
            san11__platform__pb2.ListPackagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdatePackage',
            san11__platform__pb2.UpdatePackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeletePackage',
            san11__platform__pb2.DeletePackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/SearchPackages',
            san11__platform__pb2.SearchPackagesRequest.SerializeToString,
            san11__platform__pb2.SearchPackagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateBinary',
            san11__platform__pb2.CreateBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetBinary',
            san11__platform__pb2.GetBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/BatchGetBinary',
            san11__platform__pb2.BatchGetBinaryRequest.SerializeToString,
            san11__platform__pb2.BatchGetBinaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBinaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListBinaries',
            san11__platform__pb2.ListBinariesRequest.SerializeToString,
            san11__platform__pb2.ListBinariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateBinary',
            san11__platform__pb2.UpdateBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteBinary',
            san11__platform__pb2.DeleteBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DownloadBinary',
            san11__platform__pb2.DownloadBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateImage',
            san11__platform__pb2.CreateImageRequest.SerializeToString,
            san11__platform__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateThread',
            san11__platform__pb2.CreateThreadRequest.SerializeToString,
            san11__platform__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetThread',
            san11__platform__pb2.GetThreadRequest.SerializeToString,
            san11__platform__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListThreads',
            san11__platform__pb2.ListThreadsRequest.SerializeToString,
            san11__platform__pb2.ListThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateThread',
            san11__platform__pb2.UpdateThreadRequest.SerializeToString,
            san11__platform__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteThread',
            san11__platform__pb2.DeleteThreadRequest.SerializeToString,
            san11__platform__pb2.Thread.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateComment',
            san11__platform__pb2.CreateCommentRequest.SerializeToString,
            san11__platform__pb2.Comment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListComments',
            san11__platform__pb2.ListCommentsRequest.SerializeToString,
            san11__platform__pb2.ListCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateComment',
            san11__platform__pb2.UpdateCommentRequest.SerializeToString,
            san11__platform__pb2.Comment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteComment',
            san11__platform__pb2.DeleteCommentRequest.SerializeToString,
            san11__platform__pb2.Comment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateReply',
            san11__platform__pb2.CreateReplyRequest.SerializeToString,
            san11__platform__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateReply',
            san11__platform__pb2.UpdateReplyRequest.SerializeToString,
            san11__platform__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteReply',
            san11__platform__pb2.DeleteReplyRequest.SerializeToString,
            san11__platform__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateArticle',
            san11__platform__pb2.CreateArticleRequest.SerializeToString,
            san11__platform__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetArticle',
            san11__platform__pb2.GetArticleRequest.SerializeToString,
            san11__platform__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListArticles',
            san11__platform__pb2.ListArticlesRequest.SerializeToString,
            san11__platform__pb2.ListArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateArticle',
            san11__platform__pb2.UpdateArticleRequest.SerializeToString,
            san11__platform__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteArticle',
            san11__platform__pb2.DeleteArticleRequest.SerializeToString,
            san11__platform__pb2.Article.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/SignIn',
            san11__platform__pb2.SignInRequest.SerializeToString,
            san11__platform__pb2.SignInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/SignOut',
            san11__platform__pb2.SignOutRequest.SerializeToString,
            san11__platform__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateUser',
            san11__platform__pb2.CreateUserRequest.SerializeToString,
            san11__platform__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetUser',
            san11__platform__pb2.GetUserRequest.SerializeToString,
            san11__platform__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListUsers',
            san11__platform__pb2.ListUsersRequest.SerializeToString,
            san11__platform__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateUser',
            san11__platform__pb2.UpdateUserRequest.SerializeToString,
            san11__platform__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVerificationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/SendVerificationCode',
            san11__platform__pb2.SendVerificationCodeRequest.SerializeToString,
            san11__platform__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/VerifyEmail',
            san11__platform__pb2.VerifyEmailRequest.SerializeToString,
            san11__platform__pb2.VerifyEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateNewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ValidateNewUser',
            san11__platform__pb2.ValidateNewUserRequest.SerializeToString,
            san11__platform__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdatePassword',
            san11__platform__pb2.UpdatePasswordRequest.SerializeToString,
            san11__platform__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListActivities',
            san11__platform__pb2.ListActivitiesRequest.SerializeToString,
            san11__platform__pb2.ListActivitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ToggleAction',
            san11__platform__pb2.ToggleActionRequest.SerializeToString,
            san11__platform__pb2.ToggleActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListNotifications',
            san11__platform__pb2.ListNotificationsRequest.SerializeToString,
            san11__platform__pb2.ListNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateNotification',
            san11__platform__pb2.UpdateNotificationRequest.SerializeToString,
            san11__platform__pb2.Notification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateTag',
            san11__platform__pb2.CreateTagRequest.SerializeToString,
            san11__platform__pb2.Tag.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListTags',
            san11__platform__pb2.ListTagsRequest.SerializeToString,
            san11__platform__pb2.ListTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteTag',
            san11__platform__pb2.DeleteTagRequest.SerializeToString,
            san11__platform__pb2.Tag.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatistic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetStatistic',
            san11__platform__pb2.GetStatisticRequest.SerializeToString,
            san11__platform__pb2.Statistic.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/GetAdminMessage',
            san11__platform__pb2.GetAdminMessageRequest.SerializeToString,
            san11__platform__pb2.AdminMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/CreateSubscription',
            san11__platform__pb2.CreateSubscriptionRequest.SerializeToString,
            san11__platform__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubscriptioins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/ListSubscriptioins',
            san11__platform__pb2.ListSubscriptionsRequest.SerializeToString,
            san11__platform__pb2.ListSubscriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/UpdateSubscription',
            san11__platform__pb2.UpdateSubscriptionRequest.SerializeToString,
            san11__platform__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/san11_platform.San11Platform/DeleteSubscription',
            san11__platform__pb2.DeleteSubscriptionRequest.SerializeToString,
            san11__platform__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
