FROM node:22.10

WORKDIR /app

# Copy package.json
COPY package.json ./
# Copy package-lock.json if it exists
RUN if [ -f package-lock.json ]; then cp package-lock.json .; fi

RUN npm install

COPY . .