# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import san11_platform_pb2 as san11__platform__pb2


class RouteGuideStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePackage = channel.unary_unary(
                '/routeguide.RouteGuide/CreatePackage',
                request_serializer=san11__platform__pb2.CreatePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                )
        self.UpdatePackage = channel.unary_unary(
                '/routeguide.RouteGuide/UpdatePackage',
                request_serializer=san11__platform__pb2.UpdatePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                )
        self.DeletePackage = channel.unary_unary(
                '/routeguide.RouteGuide/DeletePackage',
                request_serializer=san11__platform__pb2.DeletePackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Empty.FromString,
                )
        self.GetPackage = channel.unary_unary(
                '/routeguide.RouteGuide/GetPackage',
                request_serializer=san11__platform__pb2.GetPackageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Package.FromString,
                )
        self.ListPackages = channel.unary_unary(
                '/routeguide.RouteGuide/ListPackages',
                request_serializer=san11__platform__pb2.ListPackagesRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.ListPackagesResponse.FromString,
                )
        self.GetBinary = channel.unary_unary(
                '/routeguide.RouteGuide/GetBinary',
                request_serializer=san11__platform__pb2.GetBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                )
        self.BatchGetBinary = channel.unary_unary(
                '/routeguide.RouteGuide/BatchGetBinary',
                request_serializer=san11__platform__pb2.BatchGetBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.BatchGetBinaryResponse.FromString,
                )
        self.UploadBinary = channel.unary_unary(
                '/routeguide.RouteGuide/UploadBinary',
                request_serializer=san11__platform__pb2.UploadBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Status.FromString,
                )
        self.DownloadBinary = channel.unary_unary(
                '/routeguide.RouteGuide/DownloadBinary',
                request_serializer=san11__platform__pb2.DownloadBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Binary.FromString,
                )
        self.DeleteBinary = channel.unary_unary(
                '/routeguide.RouteGuide/DeleteBinary',
                request_serializer=san11__platform__pb2.DeleteBinaryRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Empty.FromString,
                )
        self.UploadImage = channel.unary_unary(
                '/routeguide.RouteGuide/UploadImage',
                request_serializer=san11__platform__pb2.UploadImageRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Status.FromString,
                )
        self.SignIn = channel.unary_unary(
                '/routeguide.RouteGuide/SignIn',
                request_serializer=san11__platform__pb2.SignInRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.SignInResponse.FromString,
                )
        self.SignOut = channel.unary_unary(
                '/routeguide.RouteGuide/SignOut',
                request_serializer=san11__platform__pb2.SignOutRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Status.FromString,
                )
        self.SignUp = channel.unary_unary(
                '/routeguide.RouteGuide/SignUp',
                request_serializer=san11__platform__pb2.SignUpRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.SignUpResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/routeguide.RouteGuide/GetUser',
                request_serializer=san11__platform__pb2.GetUserRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.User.FromString,
                )
        self.GetStatistic = channel.unary_unary(
                '/routeguide.RouteGuide/GetStatistic',
                request_serializer=san11__platform__pb2.GetStatisticRequest.SerializeToString,
                response_deserializer=san11__platform__pb2.Statistic.FromString,
                )


class RouteGuideServicer(object):
    """Interface exported by the server.
    """

    def CreatePackage(self, request, context):
        """package related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBinary(self, request, context):
        """Binary related 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request, context):
        """Image related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """User related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistic(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePackage,
                    request_deserializer=san11__platform__pb2.CreatePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'UpdatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePackage,
                    request_deserializer=san11__platform__pb2.UpdatePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'DeletePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePackage,
                    request_deserializer=san11__platform__pb2.DeletePackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Empty.SerializeToString,
            ),
            'GetPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPackage,
                    request_deserializer=san11__platform__pb2.GetPackageRequest.FromString,
                    response_serializer=san11__platform__pb2.Package.SerializeToString,
            ),
            'ListPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackages,
                    request_deserializer=san11__platform__pb2.ListPackagesRequest.FromString,
                    response_serializer=san11__platform__pb2.ListPackagesResponse.SerializeToString,
            ),
            'GetBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBinary,
                    request_deserializer=san11__platform__pb2.GetBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'BatchGetBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetBinary,
                    request_deserializer=san11__platform__pb2.BatchGetBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.BatchGetBinaryResponse.SerializeToString,
            ),
            'UploadBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadBinary,
                    request_deserializer=san11__platform__pb2.UploadBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Status.SerializeToString,
            ),
            'DownloadBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadBinary,
                    request_deserializer=san11__platform__pb2.DownloadBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Binary.SerializeToString,
            ),
            'DeleteBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBinary,
                    request_deserializer=san11__platform__pb2.DeleteBinaryRequest.FromString,
                    response_serializer=san11__platform__pb2.Empty.SerializeToString,
            ),
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=san11__platform__pb2.UploadImageRequest.FromString,
                    response_serializer=san11__platform__pb2.Status.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=san11__platform__pb2.SignInRequest.FromString,
                    response_serializer=san11__platform__pb2.SignInResponse.SerializeToString,
            ),
            'SignOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOut,
                    request_deserializer=san11__platform__pb2.SignOutRequest.FromString,
                    response_serializer=san11__platform__pb2.Status.SerializeToString,
            ),
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=san11__platform__pb2.SignUpRequest.FromString,
                    response_serializer=san11__platform__pb2.SignUpResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=san11__platform__pb2.GetUserRequest.FromString,
                    response_serializer=san11__platform__pb2.User.SerializeToString,
            ),
            'GetStatistic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistic,
                    request_deserializer=san11__platform__pb2.GetStatisticRequest.FromString,
                    response_serializer=san11__platform__pb2.Statistic.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Interface exported by the server.
    """

    @staticmethod
    def CreatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/CreatePackage',
            san11__platform__pb2.CreatePackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/UpdatePackage',
            san11__platform__pb2.UpdatePackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/DeletePackage',
            san11__platform__pb2.DeletePackageRequest.SerializeToString,
            san11__platform__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/GetPackage',
            san11__platform__pb2.GetPackageRequest.SerializeToString,
            san11__platform__pb2.Package.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/ListPackages',
            san11__platform__pb2.ListPackagesRequest.SerializeToString,
            san11__platform__pb2.ListPackagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/GetBinary',
            san11__platform__pb2.GetBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchGetBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/BatchGetBinary',
            san11__platform__pb2.BatchGetBinaryRequest.SerializeToString,
            san11__platform__pb2.BatchGetBinaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/UploadBinary',
            san11__platform__pb2.UploadBinaryRequest.SerializeToString,
            san11__platform__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/DownloadBinary',
            san11__platform__pb2.DownloadBinaryRequest.SerializeToString,
            san11__platform__pb2.Binary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/DeleteBinary',
            san11__platform__pb2.DeleteBinaryRequest.SerializeToString,
            san11__platform__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/UploadImage',
            san11__platform__pb2.UploadImageRequest.SerializeToString,
            san11__platform__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/SignIn',
            san11__platform__pb2.SignInRequest.SerializeToString,
            san11__platform__pb2.SignInResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/SignOut',
            san11__platform__pb2.SignOutRequest.SerializeToString,
            san11__platform__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/SignUp',
            san11__platform__pb2.SignUpRequest.SerializeToString,
            san11__platform__pb2.SignUpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/GetUser',
            san11__platform__pb2.GetUserRequest.SerializeToString,
            san11__platform__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatistic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.RouteGuide/GetStatistic',
            san11__platform__pb2.GetStatisticRequest.SerializeToString,
            san11__platform__pb2.Statistic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
